CREATE TABLE student (
    Codigo_Alumno VARCHAR(50) PRIMARY KEY,
    Doc_Alumno VARCHAR(50) NOT NULL,
    Tipo_Documento_Alumno VARCHAR(50) NOT NULL,
    Primer_Nombre_Alumno VARCHAR(50) NOT NULL,
    Segundo_Nombre_Alumno VARCHAR(50),
    Primer_Apellido_Alumno VARCHAR(50) NOT NULL,
    Segundo_Apellido_Alumno VARCHAR(50),
    Lugar_Expedicion_Alumno VARCHAR(100),
    Lugar_de_Nacimiento_Alumno VARCHAR(100),
    Depto_Nacimiento_Alumno VARCHAR(100),
    Municipio_Nacimiento_Alumno VARCHAR(100),
    Fecha_de_Nacimiento_Alumno DATE,
    Sexo_Alumno VARCHAR(10),
    Fecha_de_Ingreso_Alumno DATE,
    Email_Alumno VARCHAR(100),
    Edad_Alumno INT,
    EPS_Alumno VARCHAR(50),
    Grupo_Sanguineo_Alumno VARCHAR(5),
    RH_Alumno VARCHAR(5),
    Telefono_Alumno VARCHAR(20),
    Direccion_Residencia_Alumno VARCHAR(200),
    Barrio_Alumno VARCHAR(100),
    Estrato_Alumno VARCHAR(10),
    Grupo_Alumno VARCHAR(50),
    Grado_Alumno VARCHAR(50),
    Total_Hermanos_Alumno INT,
    Lugar_Que_Ocupa_Alumno VARCHAR(50),
    Colegio_Procedencia_Alumno VARCHAR(100),
    Nro_Matricula_Alumno VARCHAR(50),
    Madre_ID INT,
    Padre_ID INT,
    Responsable_ID INT,
    FOREIGN KEY (Madre_ID) REFERENCES mother(ID),
    FOREIGN KEY (Padre_ID) REFERENCES father(ID),
    FOREIGN KEY (Responsable_ID) REFERENCES responsable(ID)
);
